### ISSUE TITLE
ソースコードの引用が正しく表示されない

### ISSUE THREAD

**Issue by Matsuyanagi** [rust-lang-ja/book-ja-pdf#22]
2022-08-27 時点にて
https://doc.rust-jp.rs/book-ja-pdf/book.pdf
ソースコードの引用部分の多くが `{{#rustdoc_include ...` となっていて、コードが表示されていません。
以前、2022-02 頃の版では正しく表示されていました。

2022-08-27 時点
![book pdf 2022-08-27](https://user-images.githubusercontent.com/1475814/187030272-9b572c56-7a18-40cc-aef3-4b5b18eb3d67.png)

2022-02 頃
![rust pdf 2022-02](https://user-images.githubusercontent.com/1475814/187030285-aee354ee-b02b-4e74-99cb-06ff970ed47d.png)

**Comment by moriai** [comment]
mdbookで処理する前のMarkdownファイルからPDFを生成しているためにおきているようです。直してみました。 #23

**Comment by y-yu** [comment]
Fix #23

**Comment by Matsuyanagi** [comment]
修正されていることを確認しました。
対応ありがとうございました。
